### ISSUE TITLE
Incorrect folder content

### ISSUE THREAD

**Issue by CaptainQuirk** [k1LoW/emacs-cake#1]
HI, 

I'm using folders inside the app/views/elements folder and the content is displayed wrongly and uncomplete. 
Some of the files are displayed with the folder name inside the whole path name which I don't find appropriate.
Some other files aren't displayed at all, neither is their containing folder.

Thanks for your time

**Comment by k1LoW** [comment]
Hi.

Do you use `cake-open-elements-dir` ?
Provide me some specific case.

Thanks
